#Absolute path and relative path
#Absolute path - gives complete location from root directory
#Relative path - give location from the current working directory
file = open("poem.txt")
#FILE DESCRIPTOR - A token, generated by the OS that allows programs to do more operations with the file
#TO read line by line
print(file.readline())
#To read from the current position till the end
print(file.read())
#Not closing the file can lead to
#1. File system usually locks it down so no other program can use it
#2. Limited number of file descriptors that you can create before your file system runs out of them
#Race condition - when a system attempts to perform two or more operations at the same time
#3.Can lead to race condition
file.close()
#Closes the file without specifying
with open("poem.txt") as file:
    print(file.readline())