# -*- coding: utf-8 -*-
"""webScrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18TTy05JO3vsOABUR8DmB3XmMqXhodErv
"""

import pandas as pd
# reading 1 csv file from a website
df = pd.read_csv("https://www.football-data.co.uk/new/JPN.csv")
df